set nocompatible  " Let Vim be Vim.

if !has('gui_running')
  set background=dark  " The terminal's background is (almost) always dark.
endif

let &backspace = v:versionlong < 8020590 ? 2 : 3  " Backspace over everything.
set guioptions=acegim  " :help 'guioptions'
set hlsearch  " Highlight all matches when there is a search pattern.
set ignorecase smartcase  " Ignore case in patterns unless they contain caps.
set incsearch  " Search while typing.
set infercase  " Adjust the case of a match when doing completion in Insert mode.
set nolangremap  " 'langmap' does not apply to characters resulting from a mapping.
set lazyredraw  " Do not redraw while executing stuff that has not been typed.
set mouse=a  " Enable mouse in all modes.
set ruler  " Show the line and the column number of the cursor position.
set showcmd  " Show (partial) command on the last line of the screen.
set ttyfast  " All modern terminals are fast.
set wildmenu  " Show possible matches when doing completion in Command mode.
set nowrap  " Do not wrap long lines.

" Turn the bells and whistles on.
colorscheme desert
filetype indent plugin on
syntax on

" Magic!
noremap ; :
" Return to Normal mode by (fast)typing jj.
inoremap jj <Esc>
" Yank from the cursor to the EOL (same as C and D).
nnoremap Y y$

augroup Always
  au!
  au BufWritePre * %s/\s\+$//e  " Delete trailing whitespace.
augroup END

augroup Haskell
  au!
  au FileType cabal setl et sw=2  " Use the default Cabal's indentation style.
  au FileType haskell setl et sw=4  " Use the default Haskell's indentation style.
augroup END

augroup VimL
  au!
  au FileType vim setl et sw=2  " Use the default VimL's indentation style.
augroup END
