unset HISTFILE

PS1='%n@%m:%2~%# '

alias L='less -Ss'
alias m='more -Ss'
alias ls='ls -F'
alias ll='ls -l'

case $(uname) in
	Darwin)
		alias hd='hexdump -C'
		alias lx='ll -%@Oe'
		;;
	FreeBSD)
		alias lx='ll -o'
		;;
esac
